services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: thompson-sampling-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=INFO
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - thompson-network

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: thompson-admin-panel
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - thompson-network

  redis:
    image: redis:7-alpine
    container_name: thompson-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - thompson-network

volumes:
  redis_data:
    name: thompson-redis-data

networks:
  thompson-network:
    name: thompson-network
